export const RELEASE_RECORDS = [
  { version: "1.10.2", goal: "结构化分析、Word 分页与回归环境收尾", modules: ["Qwen 非思考结构任务", "双阶段连接测试", "岗位画像降级", "DOCX 显式分页", "独立 E2E 构建目录"], tests: "182 Vitest / 39 Playwright / evals / audit / build", status: "released" },
  { version: "1.10.1", goal: "A4 分页统一与一页适配", modules: ["浏览器实测分页", "真实 A4 预览", "PDF/DOCX 统一换页", "一键适配一页", "溢出门禁"], tests: "177 Vitest / 38 Playwright / evals / audit / build", status: "released" },
  { version: "1.10.0", goal: "双模式 PDF、自定义优化风格与可选关键词增强", modules: ["ATS 文字 PDF", "视觉还原 PDF", "统一渲染模型", "自定义风格", "关键词核验与补正"], tests: "171 Vitest / 37 Playwright / evals / audit / build", status: "released" },
  { version: "1.9.7", goal: "面试策略与导入数据完整性修复", modules: ["长 JD 兼容", "错误透传", "导入引用门禁", "待确认归类", "旧证据覆盖保护"], tests: "160 Vitest / 35 Playwright / evals / audit / build", status: "released" },
  { version: "1.9.6", goal: "简历导入完整识别与待确认修复", modules: ["确定性 Mock 解析", "完整导入资料", "扩展区块", "V7 备份"], tests: "155 Vitest / 35 Playwright / evals / audit / build", status: "released" },
  { version: "1.9.5", goal: "JD 决策地图与可信匹配升级", modules: ["JD 草稿确认", "逐要求事实召回", "确定性岗位准备度", "四视图原文审计", "48 条 Gold 评测"], tests: "151 Vitest / 35 Playwright / evals / audit / build", status: "released" },
  { version: "1.9.4", goal: "分析性能与任务拆分修复", modules: ["非思考结构抽取", "预测拆批", "两阶段快速分析", "按需面试策略", "性能追踪"], tests: "142 Vitest / 35 Playwright / evals / audit / build", status: "released" },
  { version: "1.9.3", goal: "深度分析超时、进度与取消修复", modules: ["有界分析执行器", "流式三阶段进度", "主动取消", "制作阶段优化"], tests: "128+ Vitest / 32+ Playwright / evals / CI", status: "released" },
  { version: "1.9.2", goal: "提示词透明工作台只读试用版", modules: ["提示词注册中心", "完整运行快照", "底层文件目录", "版本与测评关联"], tests: "119+ Vitest / 31+ Playwright / evals / CI", status: "released" },
  { version: "1.9.1", goal: "本地运行与全流程稳定性修复", modules: ["本地脚本来源", "示例数据", "AI 设置", "截断批处理降级"], tests: "108+ Vitest / 30 Playwright / CI success", commit: "0817dc6", status: "released" },
  { version: "1.9.0", goal: "岗位需求地图与深度 JD 分析", modules: ["原子岗位要求", "事实匹配", "逐条面试策略", "安全回答帮助"], tests: "validated and released", commit: "2ad1a9a", status: "released" },
  { version: "1.8.1", goal: "多模型兼容与官方模型清单修复", modules: ["结构化输出适配", "项目访谈确定性元数据", "模型清单刷新", "中文错误恢复"], tests: "97 unit + 28 e2e + evals + build", status: "released" },
  { version: "1.8.0", goal: "个人经历事实与能力底座", modules: ["项目化经历库", "原子事实与指标", "能力等级", "自适应访谈", "V4 备份"], tests: "validated and released", status: "released" },
  { version: "1.7.3", goal: "可信度与数据一致性修复", modules: ["材料修订锁", "证据候选确认", "安全 Mock", "备份恢复"], tests: "75 Vitest / 23 Playwright / CI success", commit: "d4d0a07", status: "released" },
  { version: "1.7.2", goal: "受约束的可视化工作流调整", modules: ["React Flow 编辑器", "结构护栏", "测试发布", "版本比较与回滚"], tests: "63 Vitest / 21 Playwright / local success", commit: "f83bb1a", status: "released" },
  { version: "1.7.1", goal: "Flowise 本机实验服务与项目证据草稿", modules: ["安全状态", "新手项目梳理", "DirectLLM 对比", "证据确认门禁"], tests: "54 Vitest / 20 Playwright / CI success", commit: "302ee57", status: "released" },
  { version: "1.7.0", goal: "透明化开发者工作台与本地运行追踪", modules: ["工作流地图", "运行追踪", "测评中心", "开发记录"], tests: "49 Vitest / 19 Playwright / CI success", commit: "2503bae", status: "released" },
  { version: "1.6.2", goal: "建立 AI 质量测评基线", modules: ["24 个合成案例", "确定性评分器", "CI Mock 回归"], tests: "48 Vitest / 18 Playwright / CI success", commit: "cbc431d", status: "released" },
  { version: "1.6.1", goal: "运行环境与结构维护", modules: ["Node 24", "CI", "Store 拆分"], tests: "46 Vitest / 18 Playwright", commit: "57697d8", status: "released" },
] as const;
